//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_product()
        {
            this.tbl_cart = new HashSet<tbl_cart>();
            this.tbl_invoiceDetail = new HashSet<tbl_invoiceDetail>();
        }
    
        public int pro_id { get; set; }
        public string pro_name { get; set; }
        public string pro_description { get; set; }
        public Nullable<int> pro_price { get; set; }
        public string pro_image { get; set; }
        public Nullable<int> pro_user_id_fk { get; set; }
        public Nullable<int> cat_id_fk { get; set; }
    
        public virtual tbl_categories tbl_categories { get; set; }
        public virtual tbl_user tbl_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cart> tbl_cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_invoiceDetail> tbl_invoiceDetail { get; set; }
    }
}
