//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cart
    {
        public int c_id { get; set; }
        public Nullable<int> c_qty { get; set; }
        public Nullable<int> c_price { get; set; }
        public Nullable<int> c_fk_user_id { get; set; }
        public Nullable<int> c_fk_pro_id { get; set; }
    
        public virtual tbl_product tbl_product { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
